
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 17 00:55:32 GMT-12:00 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Tkn_color = 27;
  public static final int Tkn_direccion = 14;
  public static final int Tkn_ide = 4;
  public static final int Tkn_tamaño = 26;
  public static final int Tkn_entero = 17;
  public static final int Tkn_eliminar = 21;
  public static final int Tkn_telefono = 15;
  public static final int Tkn_producto = 23;
  public static final int Tkn_propietario = 12;
  public static final int Tkn_tienda = 20;
  public static final int EOF = 0;
  public static final int Tkn_lista = 10;
  public static final int Tkn_Usuario = 3;
  public static final int Tkn_cadena = 19;
  public static final int Tkn_nombre = 13;
  public static final int error = 1;
  public static final int Tkn_marca = 25;
  public static final int Tkn_id = 18;
  public static final int Tkn_sucursal = 22;
  public static final int Tkn_registro = 5;
  public static final int Tkn_menos = 6;
  public static final int Tkn_access = 9;
  public static final int Tkn_cantidad = 24;
  public static final int Tkn_codigo = 11;
  public static final int Tkn_reply = 2;
  public static final int Tkn_precio = 28;
  public static final int Tkn_dolar = 7;
  public static final int Tkn_igual = 8;
  public static final int Tkn_modificar = 16;
}

