
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 10 15:58:44 GMT-12:00 2018
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Tkn_coC = 8;
  public static final int Tkn_coA = 7;
  public static final int Tkn_entero = 10;
  public static final int Tkn_dibujar = 9;
  public static final int EOF = 0;
  public static final int Tkn_coma = 3;
  public static final int Tkn_id = 11;
  public static final int Tkn_parC = 5;
  public static final int error = 1;
  public static final int Tkn_parA = 4;
  public static final int Tkn_igual = 2;
  public static final int Tkn_panel = 6;
  public static final int Tkn_cadena = 12;
}

