
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 20 02:33:12 GMT-12:00 2019
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 9;
  public static final int RDouble = 4;
  public static final int IGUAL = 17;
  public static final int Tkn_Else = 25;
  public static final int DECIMAL = 20;
  public static final int Tkn_While = 24;
  public static final int DIVIDIDO = 11;
  public static final int NEGACION = 22;
  public static final int RIMPRIMIR = 2;
  public static final int PARIZQ = 6;
  public static final int YLOGICO = 13;
  public static final int PARDER = 7;
  public static final int UMENOS = 21;
  public static final int POR = 10;
  public static final int EOF = 0;
  public static final int RInt = 3;
  public static final int DIFERENTE = 12;
  public static final int error = 1;
  public static final int MENQUE = 15;
  public static final int IDENTIFICADOR = 18;
  public static final int Tkn_If = 23;
  public static final int Tkn_LlaC = 26;
  public static final int ENTERO = 19;
  public static final int Tkn_LlaA = 27;
  public static final int MAYQUE = 16;
  public static final int OLOGICO = 14;
  public static final int MAS = 8;
  public static final int PTCOMA = 5;
}

