
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 20 01:01:16 GMT-12:00 2019
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int Tkn_CorC = 5;
  public static final int Tkn_CorA = 4;
  public static final int Tkn_Coma = 3;
  public static final int EOF = 0;
  public static final int ENTERO = 2;
}

